set repo_root [file normalize [file dirname [file dirname [info script]]]]
source [file join $repo_root tcl quantized_layer_profile.tcl]

set stage all
if {[info exists ::env(HLS_QUANTIZED_LAYER_INTEGRATION_STAGE)]} {
    set stage $::env(HLS_QUANTIZED_LAYER_INTEGRATION_STAGE)
}
if {$stage ni {prepare cosim all}} {
    error "HLS_QUANTIZED_LAYER_INTEGRATION_STAGE must be prepare, cosim or all"
}

set precision w4
if {[info exists ::env(QUANTIZED_LAYER_PRECISION)]} {
    set precision $::env(QUANTIZED_LAYER_PRECISION)
}
if {$precision ni {w4 w8}} {
    error "QUANTIZED_LAYER_PRECISION must be w4 or w8"
}
set profile_info [quantized_layer_profile_resolve $precision]
set profile [dict get $profile_info profile]
set profile_variant [dict get $profile_info variant]
set profile_id $profile
regsub -all {[^A-Za-z0-9_]} $profile_id _ profile_id

set trace_level port
if {[info exists ::env(QUANTIZED_LAYER_INTEGRATION_TRACE_LEVEL)]} {
    set trace_level $::env(QUANTIZED_LAYER_INTEGRATION_TRACE_LEVEL)
}
if {$trace_level ni {none port all}} {
    error "QUANTIZED_LAYER_INTEGRATION_TRACE_LEVEL must be none, port or all"
}

set clock_ns 5.000
if {[info exists ::env(QUANTIZED_LAYER_CLOCK_NS)] &&
    $::env(QUANTIZED_LAYER_CLOCK_NS) ne ""} {
    set clock_ns $::env(QUANTIZED_LAYER_CLOCK_NS)
}

# The profile worker owns the feature matrix. Keep this fixture's ABI and
# small model profile fixed, while allowing the selected profile to inject
# exact -D switches without editing this runner.
set cflags "-I$repo_root/include -std=c++14 -pthread -DQWEN_TEST_QUANTIZED_DATAFLOW -DQUANTIZED_CSIM_FEEDBACK -DMM_STREAM_QUANTIZED_NARROW_ACCUM"
append cflags " " [quantized_layer_profile_cflags $precision]
set top quantized_layer_integration_closed_loop
set matrix_file mm_stream_8x128_int4x4_block.cpp
if {$precision eq "w4"} {
    append cflags " -DMM_STREAM_8X128_INT4X4_OUTPUTS_PER_WAVE_CONFIG=128 -DMM_STREAM_8X128_INT4X4_PACKED_ACCUM_CONFIG=0"
} else {
    set top quantized_layer_integration_w8_closed_loop
    set matrix_file mm_stream_4x128_int8x8_block.cpp
    append cflags " -DMM_STREAM_QUANTIZED_SINGLE_ACCUM_BANK"
}
if {$profile eq "integrated"} { set matrix_file quantized_decode_rows.cpp }

set project_root [file join $repo_root .build hls quantized_layer_integration_closed_loop $precision $profile_id]
if {[info exists ::env(LLM_FPGA_HLS_PROJECT_ROOT)] &&
    $::env(LLM_FPGA_HLS_PROJECT_ROOT) ne ""} {
    set project_root [file normalize $::env(LLM_FPGA_HLS_PROJECT_ROOT)]
}
set project_name quantized_layer_integration_${precision}_${profile_id}
if {[info exists ::env(QUANTIZED_LAYER_INTEGRATION_PROJECT)] &&
    $::env(QUANTIZED_LAYER_INTEGRATION_PROJECT) ne ""} {
    set project_name $::env(QUANTIZED_LAYER_INTEGRATION_PROJECT)
}
file mkdir $project_root
set expected_dump [file join $project_root ${project_name}_expected.dump]
if {[info exists ::env(QUANTIZED_LAYER_EXPECTED_DUMP)] &&
    $::env(QUANTIZED_LAYER_EXPECTED_DUMP) ne ""} {
    set expected_dump [file normalize $::env(QUANTIZED_LAYER_EXPECTED_DUMP)]
}
set ::env(QUANTIZED_LAYER_EXPECTED_DUMP) $expected_dump

cd $project_root
if {$stage ne "cosim"} {
    if {[info exists ::env(QUANTIZED_LAYER_RTL_REPLAY)]} {
        unset ::env(QUANTIZED_LAYER_RTL_REPLAY)
    }
    # A fresh CSim is the source of truth for the exact arithmetic snapshot.
    # CoSim-only runs deliberately preserve the dump generated by prepare/all.
    if {[file exists $expected_dump]} {
        file delete -force $expected_dump
    }
    open_project -reset $project_name
    set_top $top
    foreach source [list ${top}.cpp \
            control_cache_quantized_${precision}_layer.cpp \
            compute_core_quantized_${precision}_unified.cpp \
            $matrix_file compute_stream.cpp] {
        add_files [file join $repo_root kernel $source] -cflags $cflags
    }
    add_files -tb [file join $repo_root tests \
        ${top}_tb.cpp] -cflags $cflags
    open_solution -reset solution1 -flow_target vitis
    set part xcu50-fsvh2104-2-e
    if {[info exists ::env(QUANTIZED_LAYER_HLS_PART)] &&
        $::env(QUANTIZED_LAYER_HLS_PART) ne ""} {
        set part $::env(QUANTIZED_LAYER_HLS_PART)
    }
    set_part $part
    create_clock -period $clock_ns -name default
    config_compile -name_max_length 256
    csim_design
    csynth_design
} else {
    set report_path [file join $project_name solution1 syn report \
        ${top}_csynth.xml]
    if {![file exists $report_path]} {
        error "Missing prepared synthesis report: $report_path"
    }
    if {![file exists $expected_dump]} {
        error "Missing CSim expected dump: $expected_dump"
    }
    open_project $project_name
    open_solution solution1
}

if {$stage ne "prepare"} {
    # Keep deadlock detection enabled. Port tracing is the default; all-port
    # tracing is available for a targeted FIFO diagnosis.
    set ::env(QUANTIZED_LAYER_RTL_REPLAY) 1
    puts "QLI COSIM START profile=$profile variant=$profile_variant precision=$precision clock_ns=$clock_ns trace=$trace_level expected_dump=$expected_dump deadlock_detection=enabled"
    cosim_design -rtl verilog -tool xsim -trace_level $trace_level
    puts "QLI COSIM PASS profile=$profile precision=$precision expected_dump=$expected_dump"
}
close_project
exit
