#ifndef LLM_FPGA_CONTROL_CACHE_QUANTIZED_W4_LAYER_HPP
#define LLM_FPGA_CONTROL_CACHE_QUANTIZED_W4_LAYER_HPP

#include "quantized_w4_layer_runtime.hpp"

void control_cache_quantized_w4_layer(
    hls::stream<mm_stream_quantized_task_word_t>& task_stream0,
    hls::stream<mm_stream_quantized_task_word_t>& task_stream1,
    hls::stream<mm_stream_quantized_task_word_t>& task_stream2,
    hls::stream<mm_stream_quantized_task_word_t>& task_stream3,
    hls::stream<quantized_w4_activation_word_t>& activation_stream0,
    hls::stream<quantized_w4_activation_word_t>& activation_stream1,
    hls::stream<quantized_w4_activation_word_t>& activation_stream2,
    hls::stream<quantized_w4_activation_word_t>& activation_stream3,
    hls::stream<quantized_w4_weight_word_t>& weight_stream0a,
    hls::stream<quantized_w4_weight_word_t>& weight_stream0b,
    hls::stream<quantized_w4_weight_word_t>& weight_stream1a,
    hls::stream<quantized_w4_weight_word_t>& weight_stream1b,
    hls::stream<quantized_w4_weight_word_t>& weight_stream2a,
    hls::stream<quantized_w4_weight_word_t>& weight_stream2b,
    hls::stream<quantized_w4_weight_word_t>& weight_stream3a,
    hls::stream<quantized_w4_weight_word_t>& weight_stream3b,
    hls::stream<quantized_w4_output_word_t>& out_stream0,
    hls::stream<quantized_w4_output_word_t>& out_stream1,
    hls::stream<quantized_w4_output_word_t>& out_stream2,
    hls::stream<quantized_w4_output_word_t>& out_stream3,
    hls::stream<quantized_vector_word_t>& vector_stream0a,
    hls::stream<quantized_vector_word_t>& vector_stream0b,
    hls::stream<quantized_vector_word_t>& vector_stream1a,
    hls::stream<quantized_vector_word_t>& vector_stream1b,
    hls::stream<quantized_vector_word_t>& vector_stream2a,
    hls::stream<quantized_vector_word_t>& vector_stream2b,
    hls::stream<quantized_vector_word_t>& vector_stream3a,
    hls::stream<quantized_vector_word_t>& vector_stream3b,
    const mm_input_block_t* hidden_input,
    mm_input_block_t* hidden_output,
    mm_input_block_t* key_cache,
    mm_input_block_t* value_cache,
    const mm_input_block_t* norm_memory,
    const mm_input_block_t* rope_memory,
    const quantized_w4_scale_word_t* scale_memory,
    const quantized_w4_weight_word_t* weight_mem0a,
    const quantized_w4_weight_word_t* weight_mem0b,
    const quantized_w4_weight_word_t* weight_mem1a,
    const quantized_w4_weight_word_t* weight_mem1b,
    const quantized_w4_weight_word_t* weight_mem2a,
    const quantized_w4_weight_word_t* weight_mem2b,
    const quantized_w4_weight_word_t* weight_mem3a,
    const quantized_w4_weight_word_t* weight_mem3b,
    unsigned int layer,
    unsigned int sequence_length,
    unsigned int request_position,
    unsigned int kv_context_length,
    unsigned int request_op,
    unsigned int prefill_block_size = QUANTIZED_LAYER_W4_TOKEN_BLOCK);

#endif
