#!/usr/bin/env python3
"""Browse stable CoWave design/configuration names and resolve build commands."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "designs/catalog.json"
FIELDS = {
    "profile": "QUANTIZED_LAYER_PROFILE",
    "rms_lanes": "QUANTIZED_LAYER_RMS_LANES",
    "silu_lanes": "QUANTIZED_LAYER_SILU_LANES",
    "weight_read_outstanding": "QUANTIZED_LAYER_WEIGHT_READ_OUTSTANDING",
    "attention_wave": "QUANTIZED_LAYER_ATTENTION_WAVE",
    "prefill_ffn_overlap": "QUANTIZED_LAYER_PREFILL_FFN_OVERLAP",
}


def read_catalog():
    return json.loads(CATALOG.read_text())


def configuration_hash(design, config):
    # This identifies the selected architecture/knobs, NOT a source revision.
    data = {"design": design["id"], **{k: config[k] for k in FIELDS if k in config}}
    return hashlib.sha256(json.dumps(data, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def source_identity(design):
    if "source_manifest" not in design:
        return None
    return hashlib.sha256((ROOT / design["source_manifest"]).read_bytes()).hexdigest()


def select(catalog, design_id, config_name=None):
    designs = [d for d in catalog["designs"] if d["id"] == design_id]
    if not designs:
        raise ValueError("Unknown design; use 'list' for canonical names")
    design = designs[0]
    if config_name is None:
        return design, None
    configs = [c for c in design["configurations"] if c["name"] == config_name]
    if not configs:
        raise ValueError("Unknown configuration for " + design_id)
    return design, configs[0]


def resolve(design, config, phase, output, prefill, weights):
    if "precision_selector" not in design:
        raise ValueError("Use the design's linked reproduction recipe for this implementation")
    precision = design["precision_selector"]
    env = {v: str(config[k]) for k, v in FIELDS.items()}
    # Separate configurations even when a caller supplies a shared artifact root.
    artifact = Path(output).expanduser().resolve() / design["id"] / config["name"]
    prefix = "VITIS_QUANTIZED_" + precision.upper() + "_LAYER"
    env.update({prefix + "_ROOT": str(artifact), "TARGET": "hw_emu", "FREQUENCY": "200"})
    env["QUANTIZED_" + precision.upper() + "_LAYER_PREFILL"] = str(prefill)
    env["QUANTIZED_" + precision.upper() + "_LAYER_WEIGHTS"] = weights
    env["QUANTIZED_" + precision.upper() + "_LAYER_BLOCK_SIZE"] = str(design["rows"])
    cmd = ["bash", "scripts/build_vitis_quantized_" + precision + "_layer.sh", phase]
    return ROOT / design["source"], env, cmd


def render(catalog):
    lines = ["# CoWave design catalog", "", "<!-- Generated by scripts/cowave.py render; edit designs/catalog.json. -->", "",
             "[Documentation](README.md) | [Architecture](architecture.md) | [Evaluation](experiments.md) | [Setup](environment.md)", "",
             "## Read a design name", "",
             "`cowave-<arithmetic>-<compute CUs>-<logical rows>-<output columns>`", "",
             "For example, `cowave-int4-4-8-128` has four compute CUs, each with an 8×128 logical matrix array. Controller/status kernels are not counted. Rows are physical query capacity, not sequence batch or prompt length. Longer prompts are processed in blocks.", "",
             "`fix16` means signed fixed point, not IEEE FP16. `int4` and `int8` mean W4A4 and W8A8 matrix operands; vector, scaling and KV arithmetic are specified separately. DSP packing is already included in logical array capacity. It is not an extra throughput multiplier.", "",
             "## Designs and reproduction", "",
             "| Design | Logical MAC/cycle | Implementation scope | Read / reproduce |", "| --- | ---: | --- | --- |"]
    for d in catalog["designs"]:
        lines.append(f"| `{d['id']}` | {d.get('peak_mac_per_cycle', 'Component-specific')} | {d['scope']} | [Design](../{d['guide']}) · [Recipe](../{d['recipe']}) · [Source](../{d['source']}/) |")
    lines += ["", "## Named configurations", "",
              "A base name identifies geometry and arithmetic. A configuration adds mechanisms and service rates. Names are stable selections, not automatically the newest or fastest version. Exact source revisions and archived run identities remain separate.", "",
              "| Design | Configuration | RMS / SiLU lanes | Outstanding | Attention wave | Prefill FFN overlap | Evidence |", "| --- | --- | --- | ---: | ---: | ---: | --- |"]
    for d in catalog["designs"]:
        for c in d["configurations"]:
            evidence = " · ".join(f"[Package {i+1}](../{p}/)" for i, p in enumerate(c["evidence"]))
            lines.append(f"| `{d['id']}` | `{c['name']}` | {str(c.get('rms_lanes', '—')) + ' / ' + str(c.get('silu_lanes', '—'))} | {c.get('weight_read_outstanding', '—')} | {c.get('attention_wave', '—')} | {c.get('prefill_ffn_overlap', '—')} | {evidence} |")
    lines += ["", "Quantized entries select the existing `integrated` profile plus the explicit overrides above. The frozen resolver, headers and per-case CFLAGS define the remaining parameters (FIFO depths, accumulators, packing, etc.); see the [source provenance and reproduction recipe](../cases/quantized-layer/README.md). The Fix16 entry groups resident-Q2.14 evidence with its individual historical source manifests; it does not imply that all runs used identical binaries.", "",
              "```bash", "python3 scripts/cowave.py list", "python3 scripts/cowave.py show cowave-int4-4-8-128 integrated-rms2-silu4-prefill-overlap", "python3 scripts/cowave.py build cowave-int4-4-8-128 integrated-rms2-silu4-prefill-overlap --phase host --dry-run", "```", "",
              "`build` uses HW Emu at a modeled 200 MHz, random weights, P66 and the design's physical block size. `--prefill`, `--weights` and `--output` change the workload/artifact destination, not the design name. Explicitly choose a configuration; no moving `latest` alias is used. See [usage](usage.md) for other execution paths.", "",
              "## Evidence and workload notation", "",
              "Every measurement must identify **design + configuration + source/binary identity + workload + timing scope**. The configuration SHA-256 shown by the tool hashes the architectural selection only; it is not a source hash or proof of validation.", "",
              "P66 is 66 prompt tokens, D1 is one real Decode query, B1 is one independent sequence, and L1 is one executed layer. P8/G2/L2 means an eight-token prompt and two sampled outputs across two layers: the prompt produces the first output, one D1 forward the second. Historical operator-sweep P1024 means only the last eight query rows against a long prefix, not a full 1024-token prefill. See [evaluation](experiments.md).", "",
              "CSim, finite-FIFO RTL CoSim, HW Emu and physical hardware are distinct evidence levels. Useful-MAC efficiency is not PE active time or FPGA resource utilization. A source release does not establish routed timing or checkpoint accuracy.", "",
              "## Legacy Label Migration", "", "Old names remain valid inside immutable results. New prose and figures use the names above; kernel symbols, operation IDs and historical manifests retain their original bytes.", "",
              "| Legacy alias | Interpretation |", "| --- | --- |"]
    for d in catalog["designs"]:
        for alias in d["aliases"]:
            lines.append(f"| `{alias}` | `{d['id']}` |")
    for alias, meaning in catalog["legacy_context"]:
        lines.append(f"| `{alias}` | {meaning} |")
    lines += ["", "**Fix16 operator diagnostics** and **Small-shape protocol tests** describe evaluation scopes within a design, not extra accelerator generations. Software release numbers in CITATION.cff likewise do not identify hardware configurations.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="action", required=True)
    sub.add_parser("list")
    render_parser = sub.add_parser("render")
    render_parser.add_argument("--check", action="store_true")
    for action in ("show", "build"):
        p = sub.add_parser(action)
        p.add_argument("design")
        p.add_argument("configuration", nargs="?" if action == "show" else None)
        if action == "build":
            p.add_argument("--phase", choices=["controller-xo", "compute-xo", "link", "host", "emconfig", "run", "all"], default="host")
            p.add_argument("--output", default=str(ROOT / "artifacts"))
            p.add_argument("--prefill", type=int, default=66)
            p.add_argument("--weights", choices=["zero", "random"], default="random")
            p.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    catalog = read_catalog()
    if args.action == "list":
        for d in catalog["designs"]:
            print(d["id"] + "\n  " + "\n  ".join(c["name"] for c in d["configurations"]))
    elif args.action == "render":
        content = render(catalog)
        target = ROOT / "docs/implementations.md"
        if args.check:
            if target.read_text() != content:
                raise ValueError("Catalog documentation is stale; run scripts/cowave.py render")
            print("COWAVE CATALOG DOCUMENTATION PASS")
        else:
            target.write_text(content)
    else:
        design, config = select(catalog, args.design, args.configuration)
        if args.action == "show":
            result = {"design": design, "configuration": config}
            if config:
                result["configuration_sha256"] = configuration_hash(design, config)
            if "source_manifest" in design:
                result["published_source_manifest_sha256"] = source_identity(design)
            print(json.dumps(result, indent=2))
            return
        if not 1 <= args.prefill <= 2047:
            raise ValueError("Prefill must be in 1..2047; leave room for one Decode token")
        cwd, env, command = resolve(design, config, args.phase, args.output, args.prefill, args.weights)
        # Reject ambiguous inherited architecture settings, including internal
        # managed/default markers left by a previously sourced profile resolver.
        conflicts = [key for key, value in os.environ.items()
                     if key.startswith(("QUANTIZED_", "VITIS_QUANTIZED_"))
                     and (key not in env or value != env[key])]
        conflicts += [k for k in ("TARGET", "FREQUENCY") if k in os.environ and os.environ[k] != env[k]]
        if conflicts:
            raise ValueError("Conflicting inherited settings; unset before selecting a named configuration: " + ", ".join(sorted(conflicts)))
        print("configuration_sha256=" + configuration_hash(design, config), flush=True)
        print("published_source_manifest_sha256=" + str(source_identity(design)), flush=True)
        print("cwd=" + str(cwd), flush=True)
        print(shlex.join(["env"] + [k + "=" + v for k, v in sorted(env.items())] + command), flush=True)
        if not args.dry_run:
            subprocess.run(["bash", "scripts/verify_source.sh"], cwd=cwd, check=True)
            subprocess.run(command, cwd=cwd, env={**os.environ, **env}, check=True)


if __name__ == "__main__":
    try:
        main()
    except (ValueError, subprocess.CalledProcessError) as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(2)
